version: '1.0.0'
services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  mqttx-web:
    image: emqx/mqttx-web:latest 
    container_name: mqttx-web
    ports:
      - "8081:80"
    restart: unless-stopped